### ISSUE TITLE
UI bug with parameter control modes

### ISSUE THREAD

**Issue by tommag** [benkuper/juce_organicui#2]
There is a UI bug in the parameter UI when choosing the control mode : switching between control modes "Expression" and "Reference" doesn't show the expression / reference sub-components. 

Resizing the panel does make them appear so I guess that is has to do with the expression / reference sub-components having the same height and not triggering a resize ?

**Comment by benkuper** [comment]
Does it happen in certain contexts or everywhere ? (e.g. only in Custom Variable or only in filters..)

**Comment by tommag** [comment]
I've seen it everywhere, on all types of parameters (bool / float). I
traced it back to ParameterEditor.cpp but I'm unsure of what to do next!

**Comment by benkuper** [comment]
Actually i can't switch at all from one to another... when i'm on another mode i don't have the context menu at all

**Comment by benkuper** [comment]
Nevermind it was an old version. This is fixed !
