### ISSUE TITLE
A suggestion for fixing negative time display

### ISSUE THREAD

**Issue by 7omas** [benkuper/juce_organicui#42]
The current implementation displays hours and minutes off by one as soon as the value goes negative.

Not a coder so this suggestion might not be at all a preferred implementation (or even functional) but the idea is to give the sign only to hour and use abs() to make sure that floor() gets the intended result.

```
String StringUtil::valueToTimeString(double timeVal, int numDecimals)
{
  int hours = copysign(floor(abs(timeVal / 3600)), timeVal);
  int minutes = floor(abs(fmod(timeVal, 3600) / 60));
  double seconds = fmod(timeVal, 60);
  if (numDecimals > 0) return String::formatted("%02i:%02i:%0" + String(6 - (numDecimals - 3)) + "." + String(numDecimals) + "f", hours, minutes, seconds);
  else return String::formatted("%02i:%02i:%02i", hours, minutes, (int)seconds);
}
```

**Comment by benkuper** [comment]
it seems that your implementation would not show the decimals if equal or below zero

**Comment by 7omas** [comment]
Thats odd, I only made changes for hours and minutes. The rest should(?) be unaffected..

**Comment by benkuper** [comment]
did you try it?
this `String::formatted("%02i:%02i:%02i", hours, minutes, (int)seconds)` tells me that it won't show decimals, only seconds as integer

**Comment by benkuper** [comment]
ah sorry misread my own code..

**Comment by benkuper** [comment]
can you post a PR ?
